modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Underground%20Beacons"
logoFile="icon.png"

[[mods]]
modId="undergroundbeacons"
version="1.1"
displayName="Underground Beacons"
displayURL="https://serilum.com/mod/underground-beacons"
authors="Rick South"
description='''Allows beacons to function underground, no matter how many solid blocks are above it.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

akanealw, Alister, Andrean Olgo, aternosorg, Cherriesaurus, MWS, t128, Tyler Behl, XAgent, ตัวตรึง พระนคร   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.undergroundbeacons]]
    modId="collective"
    mandatory=true
    versionRange="[8.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.undergroundbeacons]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.1]"
    ordering="NONE"
    side="BOTH"
